name: clean_framework
description: Clean Architecture components library, inspired on the guidelines created by Uncle Bob.
version: 0.1.2
homepage: http://acme-software.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^1.1.1

  provider: ^4.1.2

  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.6.3
  mockito: ^4.1.1