name: clean_framework
description: Clean Architecture components library, inspired on the guidelines created by Uncle Bob.
version: 0.2.5
homepage: https://acme-software.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

  equatable: ^1.2.3

  provider: ^4.3.1

  either_option: ^1.0.6

  http: ^0.12.2

  meta: ^1.1.8

dev_dependencies:
  test: ^1.14.4
  mockito: ^4.1.1
